### ISSUE TITLE
`*-blacklist` and `*-whitelist` deprecated in stylelint 13.7.0

### ISSUE THREAD

**Issue by praliedutzel** [thoughtbot/stylelint-config#33]
The release of [stylelint 13.7.0](https://github.com/stylelint/stylelint/releases/tag/13.7.0) deprecates `*-blacklist` and `*-whitelist` in favor of `*-disallowed-list` and `*-allowed-list`. With this change, the following would need to be updated with the new names:

* `declaration-property-unit-whitelist` becomes `declaration-property-unit-allowed-list`
* `declaration-property-value-blacklist` becomes `declaration-property-value-disallowed-list`

Apologies if this isn't the right format for this. If you'd prefer I make a PR, just let me know!

**Comment by enatario** [comment]
Fixed in #34
