### ISSUE TITLE
Add a CODEOWNERS file to this repository

### ISSUE THREAD

**Issue by smaboshe** [thoughtbot/stylelint-config#41]
I would like to add a CODEOWNERS file to this repository. Who would be good to have in the file? Who would like to volunteer to be added?

**Comment by smaboshe** [comment]
As the latest to people to create releases for this project, @tysongach and @enatario, would you be interested in being our initial CODEOWNERS?

**Comment by stefannibrasil** [comment]
@nickcharlton is the new codeowner 🎉 He shared his interest in the open source audit session.
